work_dir: ./work_dir/RT_GCN/NASDAQ

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  # data_path: ./data/NTU-RGB-D/xsub/train_data.npy
  # label_path: ./data/NTU-RGB-D/xsub/train_label.pkl
  data_path: ./data/NASDAQ/train_15_EOD.npy
  price_path: ./data/NASDAQ/train_15_price.npy
  label_path: ./data/NASDAQ/train_15_label.pkl
  debug: False
test_feeder_args:
  data_path: ./data/NASDAQ/test_15_EOD.npy
  price_path: ./data/NASDAQ/test_15_price.npy
  label_path: ./data/NASDAQ/test_15_label.pkl


# model
model: net.rt_gcn.Model
model_args:
  in_channels: 4
  dropout: 0.5
  # edge_importance_weighting: True
  edge_importance_weighting: 'Uniform' # Weight, Uniform, Time-aware
  graph_args:
    market: 'NASDAQ'
    relation_path: ./data/NASDAQ/NASDAQ_relation.npy
    strategy: 'uniform'

#optim
# weight_decay: 0.0001
weight_decay: 0.1
base_lr: 0.1
step: [5, 25]

# training
device: [4,0]
batch_size: 64
test_batch_size: 64
num_epoch: 100



